[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { version = "1.1", features = ["sqlx-postgres", "runtime-tokio-native-tls"] }
tokio = { version = "1.44", features = ["full"] }
warp = "0.3"
futures = "0.3"
dotenvy = "0.15" 
